---
- name: Remediate IBM MQ Queue Depth Issue
  hosts: server
  become: yes
  become_user: mqm
  vars:
    queue_name: "{{ survey_vars.queue_name }}"
    qm_name: "{{ survey_vars.qm_name }}"
  tasks:
    - name: Purge the queue if depth is too high
      shell: |
        echo "clear qlocal({{ queue_name }})" | runmqsc {{ qm_name }}
      register: clear_output

    - name: Show result of purge
      debug:
        var: clear_output.stdout_lines
