---
- name: Remediate IBM MQ Queue Depth Issue
  hosts: server
  become: yes
  become_user: mqm
  vars:
    queue_name: "{{ survey_vars.queue_name }}"
    qm_name: "{{ survey_vars.qm_name }}"
    depth_threshold: "{{ survey_vars.depth_threshold | default(100, true) }}"
  tasks:

    # - name: Check queue depth
    #   shell: |
    #     echo "display qlocal({{ queue_name }}) curdepth" | runmqsc {{ qm_name }}
    #   register: queue_depth_output

    # - name: Parse queue depth safely
    #   set_fact:
    #     curdepth: >-
    #       {{
    #         queue_depth_output.stdout_lines
    #         | select('search', 'CURDEPTH\\(\\d+\\)')
    #         | map('regex_search', 'CURDEPTH\\((\\d+)\\)', '\\1')
    #         | first | default('0') | int
    #       }}

    # - name: Debug current depth
    #   debug:
    #     msg: "Current depth of {{ queue_name }} is {{ curdepth }}"

    - name: Purge the queue if depth is too high (>= {{ depth_threshold }})
      shell: |
        echo "clear qlocal({{ queue_name }})" | runmqsc {{ qm_name }}
      # when: curdepth >= depth_threshold
      register: clear_output

    - name: Show result of purge
      debug:
        var: clear_output.stdout_lines
      # when: curdepth >= depth_threshold
 
